apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: destination-weight
  namespace: default
spec:
  destination:
    name: reviews
  route:
  - labels:
      version: v2
    weight: 25
  - labels:
      version: v1
    weight: 75

