apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default-with-abort
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v3
    weight: 100
  httpFault:
    abort:
      percent: 90
      httpStatus: 400
