apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-test-v1
  namespace: default # optional (default is "default")
spec:
  destination:
    name: reviews
    namespace: default # optional (default is metadata namespace field)
  route:
  - labels:
      version: v1
    weight: 100
