apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: confluentinc/ksql-cli:0.5
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
