apiVersion: v1
kind: Pod
metadata:
  name: ksql-cli
  namespace: kafka
spec:
  containers:
  - name: ksql
    image:  confluentinc/ksql-cli:0.5
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
